command_timeout = 1200

format = "$all"

[python]
symbol = 'îˆµ '
style = 'bold #4B8BBE'

[aws]
symbol = 'î¾ '
style = 'bold #FF9900'

[battery]
full_symbol = 'ğŸ”‹'
charging_symbol = 'â†‘ '
discharging_symbol = 'â†“ '
empty_symbol = 'ğŸª«'
