# open the file manager
[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Dotfiles ğŸ—‚ï¸"
path = "~/dotfiles"
startup_command = "nvim -c 'lua Snacks.picker.git_files()'"

[[session]]
name = "Data730 ğŸ““"
path = "~/working/data730-lecture-notebooks/"
windows = ["pixi-jupyter"]

[[window]]
name = "pixi-jupyter"
startup_script = "pixi run jupyter lab --no-browser --ip '*'"
