# open the file manager
[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Dotfiles ğŸ—‚ï¸"
path = "~/dotfiles"
startup_command = "nvim -c 'lua Snacks.picker.git_files()'"
